### PR TITLE
fix(OrtIntegration): Fix client to perform case insensitive search of component. Set default componentType to OSS in Client. Fix duplicate check to case insensitive during create new component

### LINKED ISSUE #1131: ORT integration: sw360 duplicate check too strict
... and should not care for upper/lower case writing

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Fix client to perform case insensitive search of component.
>  * Set default componentType to OSS in Client.
>  * Fix duplicate check to case insensitive during create new component.

> * Which issue is this pull request belonging to and how is it solving it? (*#1131*, *#1133*, *1152*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: 
closes #1131 #1133 #1152

         example - ./cli/build/install/ort/bin/ort --info analyze -f JSON -i ~/Desktop/project/ort/packages -o ~/Desktop/project/ort/packages/ort/analyzer.
>   - Run uploader to sw360 `./cli/build/install/ort/bin/ort --info upload-result-to-sw360 -i ~/Desktop/project/ort/packages/ort/analyzer/analyzer-result.json`
>   - Verify all projects , components , releases are created and linked to project.

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by yuvarajsanthakumar** [comment]
I have tested issues 1131 and 1133 with this PR. This PR fixes both the issues and I didn't face those errors.

File: clients/http-support/src/main/java/org/eclipse/sw360/http/RequestBodyBuilderImpl.java [hunk 1]
```diff
@@ -53,6 +55,7 @@
      */
     public RequestBodyBuilderImpl(ObjectMapper mapper) {
         this.mapper = mapper;
+        mapper.setPropertyNamingStrategy(PropertyNamingStrategy.LOWER_CAMEL_CASE);
```
Comment (smrutis1) [inline clients/http-support/src/main/java/org/eclipse/sw360/http/RequestBodyBuilderImpl.java:58]: I am not sure, but it looks like this will be applicable for all not only components. Need to make sure it does not affect others.

Comment (smrutis1) [reply clients/http-support/src/main/java/org/eclipse/sw360/http/RequestBodyBuilderImpl.java:58]: Thanks for the crosscheck and confirmation.

**Review by smrutis1 — APPROVED** [review]
Code looks good to me.
