### PR TITLE
feat(CR-UI): Enhancement & Bug fixes

### LINKED ISSUE #972: Feat(CR-UI): Clearing Request Enhancement & Fixes
1. Bold text are not displayed as expected in `CR comment`, currently it appears as `<b>comment text</b>` instead of **comment text**.
2. `CR` breadcrumb in `CR Detail/Edit` page is redirecting to `Open Moderation Request` tab, It should redirect to `Open CR` tab or `Closed CR` tab (depending on status of CR).
3. `Requesting user` should be able to re-open the `closed` clearing request.
4. Add a new `CR` status `ON_HOLD` with tool-tip: `Clearing Team is waiting for input/action from the Requesting User.`
5. Add `CR` progress bar in `Open CR` tab and in `Detail/Edit` page under `Clearing Decision` table.
   - Progress should be calculated based on Approved releases to Total release (directly linked to project).
   - Progress bar should be displayed only in `Open CR` tab, except the CR's in `NEW` status.
6. Creating a new `CR` should:
   - Add a new comment in CR, the comment will list all the linked release (Name & Id) with Clearing Status NEW.
   - Also mentioned the number of COTS components (linked release) in a CR.
   - The same information should be captured in Email being triggered when a new `CR` is created.
7. Updating (directly) `Linked Releases` of a `Project` (with CR) should:
   - Add a new comment in CR, listing all the `added` and `removed` linked releases.
   - An email should be triggering listing all the `linked releases` in `New` state and the number of `COTS` components in CR.
8. Please make `Agreed Clearing Date` non mandatory field while Editing `CR`.
9. Change Closed/Rejected `CR` email text, from `Approved` to `Closed` and `Declined` to `Rejected`.
10. Re-opening `CR` should ask for new `Preferred Clearing Date` and keep track of `Re-opened` date. Display re-open count beside the re-open date in CR Details/Edit page.
11. Remove all the three date fields (`CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`) from `Open CR` tab, and add filter w.r.t following dates:
     - `CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`, and `Last updated Date`.
     - Add similar filter for `Closed CR` tab also, also include `CR closed on` date in filter.
     - Filter should have following options:
       - `today`, `Next 7 days`, `Next 30 days`, `Last 7 days`, `Last 30 days`.
12. Add `CR-ID` & `Project Name` in subject of an email for `CR`.
13. Adding or Removing of `Attachments` from a directly linked `Release` in a `Project` should be reflected in `CR` comment.
14. Add `Priority` badge with typical sw360 color code beside `CR-ID` based on `Preferred clearing date`.
    - `P-0` badge if `Preferred clearing date` is within next 7 days.
    - `P-1` badge if `Preferred clearing date` is between next 7 to 14 days.
    - `P-2` badge if `Preferred clearing date` is between next 14 to 21 days.
    - `P-3` badge if `Preferred clearing date` is greater next 21 days.

### PR DESCRIPTION
**Pull request by akapti**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
* Which issue is this pull request belonging to and how is it solving it? -> Refer issue #972 
* Did you add or update any new dependencies that are required for your change? -> **NO**

### How To Test?
* How should these changes be tested by the reviewer? -> Refer issue #972 
* Have you implemented any additional tests? -> **NO**

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

closes #972 

Signed-off-by: Abdul Kapti <abdul.mannankapti@siemens.com>

### CODE REVIEW

File: backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java [hunk 1]
```diff
@@ -932,6 +940,49 @@ public RequestStatus updateRelease(Release release, User user, Iterable<Release.
...
+                        projectModerator.addCommentToClearingRequest(cdId, comment, user);
+                    }
+                }
+            }
+        };
+    }
+
+    private Set<String> extractAttachmentNameWithType(Set<Attachment> attachments, Collection<String> filterCriteria) {
+        return attachments.stream().filter(att -> filterCriteria.contains(att.getAttachmentContentId()))
+                .map(att -> new StringBuilder("\n\t").append(att.getFilename()).append(DatabaseHandlerUtil.SEPARATOR)
```
Comment (JaideepPalit) [inline backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java:981]: Use Platform-Independent Line Separators wherever possible.
`System.lineSeparator()`

File: backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java [hunk 2]
```diff
@@ -1145,9 +1181,15 @@ private String extractReleaseNameForClearingEmail(List<Release> releases) {
         return builder.toString();
     }
 
-    private int getTotalReleaseCount(ReleaseClearingStateSummary clearingSummary) {
-        return clearingSummary.getNewRelease() + clearingSummary.getReportAvailable() + clearingSummary.getUnderClearing()
-                + clearingSummary.getSentToClearingTool()+ clearingSummary.getApproved();
+    private String appendCompTypeToReleaseVersion(Collection<Release> releases, Set<String> cotsCompIds) {
+        Integer count = 0;
```
Comment (JaideepPalit) [inline backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java:1185]: Use `int` to prevent `Autoboxing` and `Unboxing` during increment and then convert it to string.

File: backend/src-common/src/main/resources/RejectedCREmailemplate.html [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+  ~ which is available at https://www.eclipse.org/legal/epl-2.0/
+  ~
+  ~ SPDX-License-Identifier: EPL-2.0
+-->
+<!doctype html>
+<html>
+  <body>
+	<p>*** This is an automatically generated email, please do not reply. ***</p>
+	<p>Dear SW360-user,
+	    Your clearing request with id: <b>%s</b> for the project: <b>%s</b> has been rejected by the clearing team.
```
Comment (JaideepPalit) [inline backend/src-common/src/main/resources/RejectedCREmailemplate.html:15]: looks same like `ClosedCREmailTemplate.html` . Could be merged using parameter for `rejected/closed`

File: frontend/sw360-portlet/src/main/resources/content/Language.properties [hunk 4]
```diff
@@ -217,7 +220,6 @@ component.owner=Component Owner
 components=Components
 components2=component(s)
 components.only=Components only
-components.to.be.cleared=Components to be cleared
```
Comment (JaideepPalit) [inline frontend/sw360-portlet/src/main/resources/content/Language.properties:220]: Should be removed from `Language_ja.properties`

File: libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java [hunk 5]
```diff
@@ -661,6 +662,11 @@ public static EccInformation newDefaultEccInformation(){
                 .collect(Collectors.toSet());
     }
 
+    public static int getTotalReleaseCount(ReleaseClearingStateSummary clearingSummary) {
+        return clearingSummary.getNewRelease() + clearingSummary.getReportAvailable() + clearingSummary.getUnderClearing()
+                + clearingSummary.getSentToClearingTool()+ clearingSummary.getApproved();
```
Comment (JaideepPalit) [inline libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java:667]: indentation

File: frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp [hunk 6]
```diff
@@ -58,6 +63,38 @@
...
+                            <option value="<%=ClearingRequest._Fields.TIMESTAMP%>" class="textlabel stackedLabel"><liferay-ui:message key="created.on" /></option>
+                            <option value="<%=ClearingRequest._Fields.REQUESTED_CLEARING_DATE%>" class="textlabel stackedLabel"><liferay-ui:message key="preferred.clearing.date" /></option>
+                            <option value="<%=ClearingRequest._Fields.AGREED_CLEARING_DATE%>" class="textlabel stackedLabel"><liferay-ui:message key="agreed.clearing.date" /></option>
+                            <option value="<%=ClearingRequest._Fields.MODIFIED_ON%>" class="textlabel stackedLabel"><liferay-ui:message key="last.updated.on" /></option>
+                            <option value="<%=ClearingRequest._Fields.TIMESTAMP_OF_DECISION%>" class="textlabel stackedLabel"><liferay-ui:message key="request.closed.on" /></option>
+                        </select>
+                    </div>
+                    <div class="form-group">
+                        <select class="form-control form-control-sm" id="date_range" style="display: none;">
```
Comment (JaideepPalit) [inline frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp:85]: Bootstrap class can used here `d-none`

File: frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp [hunk 7]
```diff
@@ -290,35 +431,66 @@ AUI().use('liferay-portlet-url', function () {
...
+                    span.innerHTML = "P-3";
+                    $(span).html('P-2').addClass('badge-primary');
+                } else if (validation.isValidDate(rcd, 7)) { // orange --> greater than 7 days but less than 14 days
+                    span.innerHTML = "P-3";
+                    $(span).html('P-1').addClass('badge-warning');
+                } else if (validation.isValidDate(rcd, 1)) { // red --> greater than today but less than 7 days
+                    span.innerHTML = "P-3";
+                    $(span).html('P-0').addClass('badge-danger');
+                } else { // red --> today
+                    span.innerHTML = "P-3";
```
Comment (JaideepPalit) [inline frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp:488]: Should it be P-3 for all if - else cases?

**Review by JaideepPalit — CHANGES_REQUESTED** [review]
Reviewed the PR, some minor review comments.
Need to test.

**Comment by akapti** [comment]
> Reviewed the PR, some minor review comments.
> Need to test.

Thanks, Incorporated review comments.

**Review by JaideepPalit — CHANGES_REQUESTED** [review]
Tested the PR. Kindly look into some minor issue observed during testing.

1. Bold text are not displayed as expected in `CR comment`, currently it appears as `<b>comment text</b>` instead of **comment text**.- `working fine`
2. `CR` breadcrumb in `CR Detail/Edit` page is redirecting to `Open Moderation Request` tab, It should redirect to `Open CR` tab or `Closed CR` tab (depending on status of CR). - seems to be some issue , it going to open mod req
3. `Requesting user` should be able to re-open the `closed` clearing request. - - `working fine` `Requesting user` along with `Clearing Team able to reopen request
4. Add a new `CR` status `ON_HOLD` with tool-tip: `Clearing Team is waiting for input/action from the Requesting User.` - `working fine`
5. Add `CR` progress bar in `Open CR` tab and in `Detail/Edit` page under `Clearing Decision` table.- `working fine`
   - Progress should be calculated based on Approved releases to Total release (directly linked to project).
   - Progress bar should be displayed only in `Open CR` tab, except the CR's in `NEW` status.
6. Creating a new `CR` should: - `working fine`
   - Add a new comment in CR, the comment will list all the linked release (Name & Id) with Clearing Status NEW.
   - Also mentioned the number of COTS components (linked release) in a CR.
   - The same information should be captured in Email being triggered when a new `CR` is created.
7. Updating (directly) `Linked Releases` of a `Project` (with CR) should:
   - Add a new comment in CR, listing all the `added` and `removed` linked releases.
   - An email should be triggering listing all the `linked releases` in `New` state and the number of `COTS` components in CR.
8. Please make `Agreed Clearing Date` non mandatory field while Editing `CR`.- `working fine`
9. Change Closed/Rejected `CR` email text, from `Approved` to `Closed` and `Declined` to `Rejected`. `working fine`
10. Re-opening `CR` should ask for new `Preferred Clearing Date` and keep track of `Re-opened` date. Display re-open count beside the re-open date in CR Details/Edit page. - `working fine`
11. Remove all the three date fields (`CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`) from `Open CR` tab, and add filter w.r.t following dates:
     - `CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`, and `Last updated Date`.
     - Add similar filter for `Closed CR` tab also, also include `CR closed on` date in filter.
     - Filter should have following options:
       - `today`, `Next 7 days`, `Next 30 days`, `Last 7 days`, `Last 30 days`.- `working fine` . May be for last updated on and created on - the greyed out options can be removed.
12. Add `CR-ID` & `Project Name` in subject of an email for `CR`. - `working fine`
13. Adding or Removing of `Attachments` from a directly linked `Release` in a `Project` should be reflected in `CR` comment.- `working fine`
14. Add `Priority` badge with typical sw360 color code beside `CR-ID` based on `Preferred clearing date`.
    - `P-0` badge if `Preferred clearing date` is within next 7 days.
    - `P-1` badge if `Preferred clearing date` is between next 7 to 14 days.
    - `P-2` badge if `Preferred clearing date` is between next 14 to 21 days.
    - `P-3` badge if `Preferred clearing date` is greater next 21 days.
  - Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2 ....

**Comment by akapti** [comment]
> seems to be some issue , it going to open mod req 

Fixed the issue.

> Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2

not able to reproduce the issue.

**Comment by JaideepPalit** [comment]
> > seems to be some issue , it going to open mod req
> 
> Fixed the issue.
>  - working fine

> > Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2
> 
> not able to reproduce the issue.
>  - looks like the earliest Preferred clearing date is coming to be after 7 days. Need to clarify. Maybe it can solved in a separate PR, if it is an issue
image

**Review by JaideepPalit — APPROVED** [review]
(from discussion) - merging PR and create new issue after clarification.

**Comment by akapti** [comment]
> looks like the earliest Preferred clearing date is coming to be after 7 days. 

Yes. that is expected behavior, The earliest `Preferred Clearing Date` should be greater than 7 days from the date on which `clearing request` is raised.
