### PR TITLE
fix(ReleaseUI): fix Spdx parser for License withh + sign

### LINKED ISSUE #1129: 'Show License Info' button doesn't work with spdx file export from FOSSology when there is a '+' in license name
RHEL 8, SW360 12.0
The spdx file exported by fossology will replace '+' with '%2B'.
The 'Show License Info' in Components - Releases - Clearing Details couldn't work fine with it, even the main license's name doesn't have a '+'.
The problem will make other spdx attachments which don't have '%2B' in it broken by chance. Unless user delete all spdx files with '%2B' the problem won't be solved.

### PR DESCRIPTION
**Pull request by akapti**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> Which issue is this pull request belonging to and how is it solving it?
* #1129 

> Did you add or update any new dependencies that are required for your change?
* No

Issue: closes #1129 

* `Show License Info` button in `Clearing Details` tab under `Release Details Page` should display the license with `+` sign.
* Should display `Other Licenses` as well. (from `spdx:licenseInfoInFile` tag)

> Have you implemented any additional tests?
* No

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java [hunk 1]
```diff
@@ -117,6 +122,20 @@ private static String getLocalName(String label) {
...
             // label contain invalid NCName
             if (!XMLChar.isNCName(label.charAt(i))) {
+                if (Util.splitNamespaceXML(label) == label.length()) {
+                    try {
+                        label = URLDecoder.decode(label, StandardCharsets.UTF_8.name());
+                        URL url = new URL(label);
+                        if (null != url.getRef()) {
+                            return url.getRef();
+                        } else {
+                            String path = url.getPath();
```
Comment (ravi110336) [inline backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java:132]: We can do a null check for the path variable as  well similar we did for the Ref variable, just in case to avoid any null pointer.

**Review by ravi110336 — COMMENTED** [review]
Tested and working fine one small review comment. Please check.
image

File: backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java (hunk 1 above)
Comment (akapti) [reply backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java:132]: For a valid URL, path cannot be null (can be empty string), So we don't need Null check here unlike ref which can be null.

Comment (ravi110336) [reply backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java:132]: Thanks for the clarification.
